title: Lionbite
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.736091
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#125688'
    - '#C6C7C6'
    - '#777877'
  rhythmicContrast: 0.5921255
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Lionbite
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9661654
layout_spectrum: 0.1734694
