layout_spectrum: 0.1734694
color:
  saturation: 0.736091
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#DED9D6'
    - '#280B16'
    - '#9A8780'
    - '#88281F'
    - '#FDFA5C'
  rhythmicContrast: 0.5921255
typography_spectrum: 0.9661654
name: Lionbite
